services:
  postgres:
    image: postgres:15
    container_name: magalu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: magaludb
      POSTGRES_USER: magalu
      POSTGRES_PASSWORD: magalu123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: